const prompt = require('prompt-sync')();
console.log("--- Apuração de Votos ---");
const v1 = parseInt(prompt("Votos válidos para o candidato 1: "));
const v2 = parseInt(prompt("Votos válidos para o candidato 2: "));
const v3 = parseInt(prompt("Votos válidos para o candidato 3: "));
const nulos = parseInt(prompt("Quantidade de votos nulos: "));
const brancos = parseInt(prompt("Quantidade de votos em branco: "));
const totalEleitores = v1 + v2 + v3 + nulos + brancos;
const p1 = (v1 / totalEleitores) * 100;
const p2 = (v2 / totalEleitores) * 100;
const p3 = (v3 / totalEleitores) * 100;
const pNulos = (nulos / totalEleitores) * 100;
const pBrancos = (brancos / totalEleitores) * 100;
console.log(`\nTotal de eleitores: ${totalEleitores};`);
console.log(`Percentual de votos válidos:`);
console.log(`Candidato 1 = ${p1.toFixed(2)}%,`);
console.log(`Candidato 2 = ${p2.toFixed(2)}%,`);
console.log(`Candidato 3 = ${p3.toFixed(2)}%;`);
console.log(`Percentual de votos nulos: ${pNulos.toFixed(2)}%;`);
console.log(`Percentual de votos em branco: ${pBrancos.toFixed(2)}%`);